export { default as Home } from './Home/Home';
export { default as Change } from './Change/Change';
export { default as EmailConfirmed } from './EmailConfirmed/EmailConfirmed';
export { default as Explore } from './Explore/Explore';
export { default as Login } from './Login/Login';
export { default as MyPage } from './MyPage/MyPage';
export { default as New } from './New/New';
export { default as Search } from './Search/Search';
export { default as SignUp } from './SignUp/SignUp';
